# Generated by Django 5.2.5 on 2025-09-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_alt_mobile_number_user_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uploaded_resume',
            new_name='cv',
        ),
        migrations.AddField(
            model_name='user',
            name='buddy_days',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='buddy_time',
            field=models.CharField(blank=True, choices=[('9:00-10:00', '9:00 AM — 10:00 AM'), ('10:00-11:00', '10:00 AM — 11:00 AM'), ('11:00-12:00', '11:00 AM — 12:00 PM'), ('12:00-13:00', '12:00 PM — 1:00 PM'), ('13:00-14:00', '1:00 PM — 2:00 PM'), ('14:00-15:00', '2:00 PM — 3:00 PM'), ('15:00-16:00', '3:00 PM — 4:00 PM')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='can_candidates_visit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_Trainer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_candidate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single/Unmarried', 'Single/Unmarried'), ('Married', 'Married')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_desc',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='training_time',
            field=models.CharField(blank=True, choices=[('8:00-9:00', '8:00 AM — 9:00 AM'), ('9:00-10:00', '9:00 AM — 10:00 AM'), ('10:00-11:00', '10:00 AM — 11:00 AM'), ('11:00-12:00', '11:00 AM — 12:00 PM'), ('12:00-13:00', '12:00 PM — 1:00 PM'), ('13:00-14:00', '1:00 PM — 2:00 PM'), ('14:00-15:00', '2:00 PM — 3:00 PM'), ('15:00-16:00', '3:00 PM — 4:00 PM'), ('16:00-17:00', '4:00 PM — 5:00 PM'), ('17:00-18:00', '5:00 PM — 6:00 PM'), ('18:00-19:00', '6:00 PM — 7:00 PM'), ('19:00-20:00', '7:00 PM — 8:00 PM'), ('20:00-21:00', '8:00 PM — 9:00 PM'), ('21:00-22:00', '9:00 PM — 10:00 PM')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_updates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='willing_to_visit',
            field=models.BooleanField(default=False),
        ),
    ]
