# Generated by Django 5.2.5 on 2025-09-09 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_uploaded_resume_user_cv_user_buddy_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='whatsapp_updates',
            new_name='is_whatsapp_available',
        ),
    ]
