# Generated by Django 5.2.5 on 2025-09-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_whatsapp_updates_user_is_whatsapp_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single / Unmarried', 'Single / Unmarried'), ('Married', 'Married')], max_length=50, null=True),
        ),
    ]
