# Generated by Django 5.2.5 on 2025-09-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_user_joined_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_Trainer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_candidate',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('trainer', 'Trainer'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
