# Generated by Django 5.2.5 on 2025-09-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_user_is_trainer_remove_user_is_candidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Mentor', 'Mentor'), ('Candidate', 'Candidate')], default='Candidate', max_length=20),
        ),
    ]
