# Generated by Django 5.2.6 on 2025-09-11 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('buddy', models.ForeignKey(blank=True, limit_choices_to={'role': 'Trainer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buddy_assignments', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(limit_choices_to={'role': 'Candidate'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(blank=True, limit_choices_to={'role': 'Trainer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
