# Generated by Django 5.2.6 on 2025-09-11 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_candidateassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateassignment',
            name='buddy',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buddy_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidateassignment',
            name='trainer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
