# Generated by Django 5.2.6 on 2025-09-12 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_candidateassignment_buddy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paid_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SessionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('session_date', models.DateTimeField()),
                ('completed_status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Requested', 'Requested'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_name', models.CharField(choices=[('Silver', 'Silver'), ('Bronze', 'Bronze'), ('Gold', 'Gold'), ('Diamond', 'Diamond'), ('Custom', 'Custom')], default='Bronze', max_length=20)),
                ('one_to_one_training', models.BooleanField(default=False)),
                ('interview_buddy_coins_remaining', models.PositiveIntegerField(default=0)),
                ('interview_buddy_coins_used', models.PositiveIntegerField(default=0)),
                ('special_customer', models.BooleanField(default=False)),
                ('extra_features', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
