# Generated by Django 5.2.6 on 2025-09-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_user_paid_customer_sessionhistory_usersubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='one_to_one_progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='weeks_completed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
