# Generated by Django 5.2.6 on 2025-09-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_usersubscription_one_to_one_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='interview_buddy_slots_remaining',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
