# Generated by Django 5.2.6 on 2025-09-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_usersubscription_interview_buddy_slots_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='subscription_domain',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subscription_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subscription_type',
            field=models.CharField(choices=[('Silver', 'Silver'), ('Bronze', 'Bronze'), ('Gold', 'Gold'), ('Diamond', 'Diamond'), ('Custom', 'Custom')], default='Bronze', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
