# Generated by Django 5.2.6 on 2025-09-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_websitestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitestatus',
            name='website_status',
            field=models.CharField(default='toggle_website_status', max_length=50),
        ),
    ]
