# Generated by Django 5.2.6 on 2025-09-23 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_ticketresponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='created_by',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='message',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='related_OrderId',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(default='candidate', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticketID',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('Awaiting', 'Awaiting'), ('Resolved', 'Resolved')], default='Open', max_length=20),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='myapp.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='TicketResponse',
        ),
    ]
