# Generated by Django 5.2.6 on 2025-09-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_rename_created_by_ticket_user_remove_ticket_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('core', 'Core'), ('alacarte', 'A La Carte')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('features', models.TextField(blank=True, help_text='Comma separated list of features', null=True)),
                ('applicable_domains', models.TextField(blank=True, help_text='Comma separated list of domains', null=True)),
            ],
        ),
    ]
