# Generated by Django 5.2.6 on 2025-09-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='custom_id',
        ),
    ]
