# Generated by Django 5.2.6 on 2025-09-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_remove_service_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('core', 'core'), ('alacarte', 'alacarte')], max_length=20),
        ),
    ]
