# Generated by Django 5.2.6 on 2025-09-29 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponCode', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('discountType', models.CharField(choices=[('fixed', 'fixed'), ('percentage', 'Percentage')], max_length=20)),
                ('discountValue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minOrderValue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maxDiscountValue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('startAt', models.DateTimeField()),
                ('endAt', models.DateTimeField()),
                ('isActive', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('usageLimit', models.IntegerField(blank=True, null=True)),
                ('usedCount', models.IntegerField(default=0)),
                ('isFeatured', models.BooleanField(default=False)),
                ('displayPages', models.CharField(blank=True, max_length=255, null=True)),
                ('productId', models.IntegerField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_created', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
