# Generated by Django 5.2.6 on 2025-09-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='displayPages',
            field=models.CharField(blank=True, help_text='Comma separated list of pages', max_length=255, null=True),
        ),
    ]
