# Generated by Django 5.2.6 on 2025-09-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_coupon_displaypages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discountType',
            field=models.CharField(choices=[('fixed', 'fixed'), ('percentage', 'percentage')], max_length=20),
        ),
    ]
